version: '3.8'

# minio console : https://localhost:8888/ ; login: minio / minio1234

services:
  nginx:
    image: nginx:alpine-slim
    networks:
      - minio
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80
    environment:
      TZ: Europe/Paris

  minio:
    image: minio/minio:latest
    networks:
      - minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:8888/console/"
      CONSOLE_SUBPATH: /console/
      TZ: Europe/Paris

    volumes:
      - data:/data

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  minio:
    driver: bridge

volumes:
  data:
